---
kind: pipeline
type: docker
name: build_and_deploy

trigger:
  event: [ push ]
  branch: [ main ]

steps:
  # 1) Build & push image to GHCR
  - name: build-push-ghcr
    image: plugins/docker
    settings:
      registry: ghcr.io
      repo: ghcr.io/${DRONE_REPO_OWNER,,}/${DRONE_REPO_NAME,,}
      tags:
        - latest
        - ${DRONE_COMMIT_SHA}
      username:
        from_secret: GHCR_USERNAME          # <-- secret name (not value)
      password:
        from_secret: GHCR_TOKEN             # <-- secret name (not value)
      dockerfile: Dockerfile
      context: .

  # 2) Deploy on the same server
  - name: deploy
    image: docker:27-cli
    environment:
      GHCR_USERNAME:
        from_secret: GHCR_USERNAME
      GHCR_TOKEN:
        from_secret: GHCR_TOKEN
      IMAGE: ghcr.io/${DRONE_REPO_OWNER,,}/${DRONE_REPO_NAME,,}:latest
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin
      - docker pull "$IMAGE"
      - docker compose pull                 # Compose v2 is `docker compose`
      - docker compose up -d

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
