---
kind: pipeline
type: docker
name: build_and_deploy

trigger:
  event:
    - push
  branch:
    - main

steps:
  - name: debug-tree
    image: alpine:3.20
    commands:
      - pwd
      - ls -la
      - find . -maxdepth 3 -type d -print

  - name: build-push-ghcr
    image: plugins/docker
    settings:
      registry: ghcr.io
      repo: "ghcr.io/${DRONE_REPO_OWNER,,}/${DRONE_REPO_NAME,,}-frontend"
      tags:
        - latest
        - "${DRONE_COMMIT_SHA}"
      username:
        from_secret: GHCR_USERNAME
      password:
        from_secret: GHCR_TOKEN
      dockerfile: WaterlooStar/frontend/Dockerfile   # <— fixed
      context: WaterlooStar/frontend                 # <— fixed

  - name: deploy
    image: docker:27-cli
    environment:
      GHCR_USERNAME:
        from_secret: GHCR_USERNAME
      GHCR_TOKEN:
        from_secret: GHCR_TOKEN
      IMAGE: "ghcr.io/${DRONE_REPO_OWNER,,}/${DRONE_REPO_NAME,,}-frontend:latest"
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin
      - docker pull "$IMAGE"
      - docker compose -f frontend/docker-compose.yml pull
      - docker compose -f frontend/docker-compose.yml up -d

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
