---
kind: pipeline
type: docker
name: build_and_deploy

# optional: only run on main branch pushes
trigger:
  event:
    - push
  branch:
    - main

steps:
  # 1) Build & push image to GHCR
  - name: build-push-ghcr
    image: plugins/docker
    settings:
      registry: ghcr.io
      repo: ghcr.io/${DRONE_REPO_OWNER,,}/${DRONE_REPO_NAME,,}   # lowercased
      tags:
        - latest
        - ${DRONE_COMMIT_SHA}
      username:
        from_secret: GHCR_USERNAME
      password:
        from_secret: GHCR_TOKEN
      dockerfile: Dockerfile
      context: .
      # If you want BuildKit buildx/multi-arch later, swap to plugins/buildx.

  # 2) Deploy on the SAME server: docker login, pull, compose up -d
  - name: deploy
    image: docker:27-cli
    environment:
      GHCR_USERNAME:
        from_secret: GHCR_USERNAME
      GHCR_TOKEN:
        from_secret: GHCR_TOKEN
      IMAGE: ghcr.io/${DRONE_REPO_OWNER,,}/${DRONE_REPO_NAME,,}:latest
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin
      - docker pull "$IMAGE"
      # If your compose file lives at the repo root:
      - docker compose pull
      - docker compose up -d

# host volume mount to talk to the host dockerd
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
